---
title: "Carbon Dioxide Concentrations at Mona Loa Observatory"
author: "Zolal Ayazpour"
date: "10/17/2019"
output: 
  html_document: default
  github_document: default
  powerpoint_presentation: default
  word_document: default
---

## Annual Mean Carbon Dioxide Concentrations 1959-Present

```{r setup, include=TRUE, echo=FALSE, warning=FALSE, message=FALSE}
library(tidyverse)
co2_annual <- read_table("ftp://aftp.cmdl.noaa.gov/products/trends/co2/co2_annmean_mlo.txt",col_names = FALSE,skip=57)
colnames(co2_annual)=c("year","mean","unc")
ggplot(co2_annual,aes(year,mean))+
  geom_line()+
  xlab("Year")+
  ylab("Mauna Loa Annual Mean co_2 (ppm)")
```

## Top Five Annual Mean Carbon Dioxide Concentrations at Mona Loa

```{r, include=TRUE, echo=FALSE, warning=FALSE, message=FALSE}
library(knitr)
library(kableExtra)

kable(co2_annual[nrow(co2_annual):(nrow(co2_annual)-4),1:2], format="html", col.names = c("year","mean")) %>%
  kable_styling("striped", full_width = F, position="center") %>%
  row_spec(1,color="red")
```

